### ISSUE TITLE
Footer looks weird with company included

### ISSUE THREAD

**Issue by banfai** [bedapub/designit#1]
https://github.com/bedapub/designit/blob/55bca858cd38c0e4f56eb8c13b31cfd74ef17953/pkgdown/_pkgdown.yml#L3

add this:
```
authors:
  footer:
    roles: [cre, aut]
```

@idavydov @ingitwetrust @julianesiebourg
1) do we want to add links to our names? (e.g. github or something else) (❤️)
2) do we want to include the Roche logo (like RStudio) (🚀)

**Comment by idavydov** [comment]
No strong preference for both points. If we go for option 1, I would go for my github profile page.
