### ISSUE TITLE
Why is generative-vignette branch still there?

### ISSUE THREAD

**Issue by banfai** [bedapub/designit#56]
it seems there are a lot unmerged changes still (25 commits ahead)

**Comment by idavydov** [comment]
most likely because of rebasing. it 24 ahead and 25 behind

**Comment by banfai** [comment]
I'm lost...
the false positives vignette is not here: https://bedapub.github.io/designit/

**Comment by idavydov** [comment]
https://bedapub.github.io/designit/dev/articles/false_positives.html ?

or am i missing something

**Comment by banfai** [comment]
> https://bedapub.github.io/designit/dev/articles/false_positives.html ?
> 
> or am i missing something
no, I was missing the /dev/ 🤦
